block.1001=minecraft:oak_leaves
block.1002=minecraft:birch_leaves
block.1003=minecraft:spruce_leaves
block.1004=minecraft:jungle_leaves
block.1005=minecraft:acacia_leaves
block.1006=minecraft:dark_oak_leaves
block.1007=minecraft:azalea_leaves
block.1008=minecraft:cherry_leaves
block.1009=minecraft:pale_oak_leaves
block.1010=minecraft:mangrove_leaves
block.1011=minecraft:flowering_azalea_leaves
block.2001=minecraft:short_grass
block.2002=minecraft:tall_grass
block.2003=minecraft:fern
block.2004=minecraft:large_fern
block.2005=minecraft:vines
block.2006=minecraft:bush
block.2007=minecraft:dead_bush
block.2008=minecraft:short_dry_grass
block.2009=minecraft:sunflower
block.2010=minecraft:allium
block.2011=minecraft:lilac
block.2012=minecraft:torchflower
block.2013=minecraft:bamboo
block.2014=minecraft:rose_bush
block.2015=minecraft:firefly_bush
block.3001=minecraft:wheat:age=5
block.3002=minecraft:wheat:age=6
block.3003=minecraft:wheat:age=7
block.3004=minecraft:wheat:age=5
block.3005=minecraft:potatoes:age=5
block.3006=minecraft:potatoes:age=6
block.3007=minecraft:potatoes:age=7
block.3008=minecraft:carrots:age=6
block.3009=minecraft:carrots:age=7
block.3010=minecraft:beetroots:age=6
block.3011=minecraft:beetroots:age=7