block.1001=minecraft:oak_leaves
block.1002=minecraft:birch_leaves
block.1003=minecraft:spruce_leaves
block.1004=minecraft:jungle_leaves
block.1005=minecraft:acacia_leaves
block.1006=minecraft:dark_oak_leaves
block.1007=minecraft:azalea_leaves
block.1008=minecraft:cherry_leaves
block.1009=minecraft:pale_oak_leaves
block.1010=minecraft:mangrove_leaves
block.1011=minecraft:flowering_azalea_leaves
block.2001=minecraft:short_grass
block.2002=minecraft:tall_grass
block.2003=minecraft:fern
block.2004=minecraft:large_fern
block.2005=minecraft:vines
block.2006=minecraft:bush
block.2007=minecraft:dead_bush
block.2008=minecraft:short_dry_grass
block.2009=minecraft:sunflower
block.2010=minecraft:allium
block.2011=minecraft:lilac
block.2012=minecraft:torchflower
block.2013=minecraft:bamboo
block.2014=minecraft:rose_bush
block.2015=minecraft:firefly_bush
block.2016=minecraft:orange_tulip
block.2017=minecraft:pink_tulip
block.2018=minecraft:red_tulip
block.2019=minecraft:oxeye_daisy
block.2020=minecraft:poppy
block.2021=minecraft:blue_orchid
block.2022=minecraft:lily_of_the_valley
block.2023=minecraft:cornflower
block.2024=minecraft:open_eyeblossom
block.2025=minecraft:closed_eyeblossom
block.2026=minecraft:azure_bluet
block.2027=minecraft:dandelion
block.2028=minecraft:white_tulip
block.2029=minecraft:golden_dandelion
block.3001=minecraft:wheat:age=5
block.3002=minecraft:wheat:age=6
block.3003=minecraft:wheat:age=7
block.3004=minecraft:wheat:age=5
block.3005=minecraft:potatoes:age=5
block.3006=minecraft:potatoes:age=6
block.3007=minecraft:potatoes:age=7
block.3008=minecraft:carrots:age=6
block.3009=minecraft:carrots:age=7
block.3010=minecraft:beetroots:age=2
block.3011=minecraft:beetroots:age=3
block.3012=minecraft:beetroots:age=4