useNormals=true
useSpecular=false
useMaterials=true
vignette=off
separateAo=true
shadowTerrain=true
shadowEntities=true
shadowTranslucent=true
shadowBlockEntities=true
oldLighting=false
oldHandLight=true
particles.before.deferred=true
shadowMapResolution=2048
shadowDistance=128.0
shadowIntervalSize=1.0